---
title: "Data Manipulation"
output: github_document
---

```{r setup, echo = FALSE, message = FALSE}
library(tidyverse)
```

This document will show how to *manipulate* data. 

Import the two datasets that we are going to manipulate

```{r}
litters_df = read_csv("data/FAS_litters.csv", na = c("NA", "", "."))

litters_df = janitor::clean_names(litters_df)

pups_df = read_csv("data/FAS_pups.csv", na = c("NA", "", "."))

pups_df = janitor::clean_names(pups_df)
```


## 'select'

Use 'select()' to select variables

```{r}
select(litters_df, group, litter_number, gd0_weight)
```


```{r}
select(litters_df, group:gd18_weight)
```

```{r}
select(litters_df, -pups_survive)
```

```{r}
select(litters_df, -(group:gd18_weight))
```

```{r}
select(litters_df, starts_with("gd"))
```

```{r}
select(litters_df, contains("pups"))
```


```{r}
select(litters_df, GROUP = group)

rename(litters_df, GROUP = group)

select(litters_df, litter_number, gd0_weight, everything())

relocate(litters_df, litter_number, gd0_weight)
```

```{r}
select(pups_df, litter_number, sex, pd_ears)
```

## 'filter'
```{r}
filter(litters_df, gd_of_birth == 20)
```

```{r}
filter(litters_df, pups_born_alive >8)
```

```{r}
filter(litters_df, pups_born_alive !=9)
```

```{r}
filter(litters_df, group =='Con7')

filter(litters_df, group %in% c("Low7", "Low8"))
```

```{r}
filter(litters_df, group %in% c("Low7", "Low8"), pups_born_alive == 8)
```

```{r}
drop_na(litters_df, gd0_weight)
```

```{r}
filter(pups_df, sex == 1)
```

```{r}
filter(pups_df, sex == 2, pd_walk < 11)
```


## 'mutate'
```{r}
mutate(litters_df, wt_gain = gd18_weight - gd0_weight)
```

```{r}
mutate(litters_df, group = str_to_lower(group))
```

```{r}
mutate(litters_df,
       wt_gain = gd18_weight - gd0_weight, 
       group = str_to_lower(group)
       )
```


## 'arrange'
```{r}
arrange(litters_df, desc(gd0_weight))
```

```{r}
arrange(litters_df)
```


##PIPING

```{r}
litters_df = read_csv("data/FAS_litters.csv", na = c("NA", "", "."))

litters_df = janitor::clean_names(litters_df)

litters_df_var = select(litters_df, -pups_born_alive)

litters_with_filter = filter(litters_df_var, group == "Con7")

litters_wt_gain = mutate(litters_with_filter, wt_gain = gd18_weight - gd0_weight)
```

DO THIS 

```{r}
litters_df = read_csv("data/FAS_litters.csv", na = c("NA", "", ".")) 
```


